# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200)),
                ('sort_int', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('sort_int', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('subwayDescription', models.CharField(default='', max_length=200)),
                ('rent_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('seats', models.CharField(default='', max_length=200)),
                ('decoration', models.CharField(max_length=200)),
                ('userTime', models.CharField(max_length=200)),
                ('floorNum', models.IntegerField()),
                ('priceInclude', models.CharField(max_length=200)),
                ('telephone', models.CharField(default='', max_length=200)),
                ('totalArea', models.IntegerField()),
                ('blockNum', models.IntegerField()),
                ('carNum', models.IntegerField()),
                ('level', models.CharField(default='', max_length=200)),
                ('floorHeight', models.IntegerField()),
                ('elevatorNum', models.IntegerField()),
                ('propertyCompany', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('createTime', models.DateTimeField(verbose_name='date published')),
                ('buildTime', models.DateTimeField(verbose_name='date published')),
                ('sortNum', models.IntegerField(default=0)),
                ('seeNum', models.IntegerField(default=0)),
                ('location', models.CharField(default='0.0', max_length=200)),
                ('image1', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image2', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image3', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image4', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image5', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image6', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontsite.Country')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontsite.CmsStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('subway_str', models.CharField(default='', max_length=200)),
                ('country_str', models.CharField(default='', max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('rentType', models.CharField(max_length=200)),
                ('payType', models.CharField(max_length=200)),
                ('currentStatus', models.CharField(max_length=200)),
                ('heatingType', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('createTime', models.DateTimeField(verbose_name='date published')),
                ('sortNum', models.IntegerField(default=0)),
                ('seeNum', models.IntegerField(default=0)),
                ('location', models.CharField(default='0.0', max_length=200)),
                ('image1', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image2', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image3', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image4', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image5', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('image6', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontsite.Country')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_direction', models.CharField(max_length=200)),
                ('sort_int', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200)),
                ('sort_int', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subway_name', models.CharField(max_length=200)),
                ('sort_int', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='rent',
            name='roomDirection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontsite.RoomDirection'),
        ),
        migrations.AddField(
            model_name='rent',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontsite.RoomType'),
        ),
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontsite.CmsStatus'),
        ),
        migrations.AddField(
            model_name='rent',
            name='subway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontsite.Subway'),
        ),
        migrations.AddField(
            model_name='officebuilding',
            name='subway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontsite.Subway'),
        ),
    ]
