# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publish', '0001_initial'),
        ('commonData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=200, verbose_name='\u624b\u673a\u53f7')),
                ('password', models.CharField(max_length=200, verbose_name='\u5bc6\u7801')),
                ('nickname', models.CharField(max_length=200, verbose_name='\u6635\u79f0')),
                ('realname', models.CharField(max_length=200, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('IDNum', models.CharField(max_length=200, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('card', models.CharField(max_length=200, verbose_name='\u94f6\u884c\u5361\u53f7')),
                ('address', models.CharField(max_length=200, verbose_name='\u5730\u5740')),
                ('date published', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('sex', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.Sex', verbose_name='\u6027\u522b')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.Status', verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessLicence', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='\u8425\u4e1a\u6267\u7167')),
                ('corporateCharter', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='\u6cd5\u4eba\u8bc1\u4ef6')),
                ('telephone', models.CharField(max_length=200, verbose_name='\u5bf9\u63a5\u4eba\u7535\u8bdd')),
                ('serviceContent', models.CharField(max_length=200, verbose_name='\u4e3b\u8981\u670d\u52a1\u5185\u5bb9')),
                ('date published', models.DateTimeField(verbose_name='\u4fe1\u606f\u53d1\u5e03\u65f6\u95f4')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontsite.Account', verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'verbose_name': '\u6ce8\u518c\u4f01\u4e1a',
                'verbose_name_plural': '\u6ce8\u518c\u4f01\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='HouseRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u7528\u6237\u59d3\u540d')),
                ('telephone', models.CharField(max_length=200, verbose_name='\u7528\u6237\u624b\u673a\u53f7')),
                ('description', models.CharField(max_length=200, verbose_name='\u9700\u6c42\u63cf\u8ff0')),
                ('date published', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.Status', verbose_name='\u72b6\u6001')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontsite.Account', verbose_name='\u521b\u5efa\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9700\u6c42',
                'verbose_name_plural': '\u7528\u6237\u9700\u6c42',
            },
        ),
        migrations.CreateModel(
            name='HouseSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u623f\u6e90\u540d\u79f0')),
                ('address', models.CharField(max_length=200, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('areaNum', models.IntegerField(verbose_name='\u5efa\u7b51\u9762\u79ef')),
                ('rent_all_type', models.CharField(max_length=200, verbose_name='\u51fa\u79df\u6237\u578b')),
                ('description', models.CharField(max_length=200, verbose_name='\u623f\u6e90\u63cf\u8ff0')),
                ('corporationList', models.CharField(max_length=200, verbose_name='\u5165\u4fe1\u4f01\u4e1a')),
                ('date published', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('image1', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='\u56fe\u72471')),
                ('image2', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='\u56fe\u72472')),
                ('image3', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='\u56fe\u72473')),
                ('image4', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='\u56fe\u72474')),
                ('image5', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='\u56fe\u72475')),
                ('image6', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='\u56fe\u72476')),
                ('area_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.Area', verbose_name='\u6240\u5728\u5730\u533a')),
                ('decorate_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.DecorateDegree', verbose_name='\u88c5\u4fee\u7a0b\u5ea6')),
                ('district_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.District', verbose_name='\u6240\u5728\u8857\u9053')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.Status', verbose_name='\u72b6\u6001')),
                ('use_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.UseType', verbose_name='\u623f\u6e90\u7528\u9014')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontsite.Account', verbose_name='\u521b\u5efa\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u623f\u6e90',
                'verbose_name_plural': '\u7528\u6237\u623f\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='\u4fe1\u606f\u6807\u9898')),
                ('body', models.CharField(max_length=2000, verbose_name='\u4fe1\u606f\u5185\u5bb9')),
                ('date published', models.DateTimeField(verbose_name='\u4fe1\u606f\u53d1\u5e03\u65f6\u95f4')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_fromuser_account', to='frontsite.Account', verbose_name='\u53d1\u4ef6\u4eba')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonData.Status', verbose_name='\u72b6\u6001')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_touser_account', to='frontsite.Account', verbose_name='\u6536\u4ef6\u4eba')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_userid_account', to='frontsite.Account', verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'verbose_name': '\u6d88\u606f\u4e2d\u5fc3',
                'verbose_name_plural': '\u6d88\u606f\u4e2d\u5fc3',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date published', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('officeBuilding', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publish.OfficeBuildingList', verbose_name='\u623f\u6e90')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.Status', verbose_name='\u72b6\u6001')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontsite.Account', verbose_name='\u521b\u5efa\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6240\u6709\u8ba2\u5355',
                'verbose_name_plural': '\u6240\u6709\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u7528\u6237\u59d3\u540d')),
                ('telephone', models.CharField(max_length=200, verbose_name='\u7528\u6237\u624b\u673a\u53f7')),
                ('description', models.CharField(max_length=200, verbose_name='\u9700\u6c42\u63cf\u8ff0')),
                ('date published', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonData.Status', verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u9700\u6c42',
                'verbose_name_plural': '\u670d\u52a1\u9700\u6c42',
            },
        ),
    ]
